### ISSUE TITLE
[Feature]: Group 관련 기능 구현

### ISSUE THREAD

**Issue by InHyeok-J** [Endless-Creation-32nd/refill-back#14]
## 기능 설명

- 그룹 생성
- 내가 참여한 그룹 조회
- 추천 그룹 조회 (4개)
- 그룹 1개 상세 조회
- 그룹 참여

## Tasks

- [x] 그룹 생성
- [x] 내가 참여한 그룹 조회
- [x] 추천 그룹 조회
- [x] 그룹 1개 상세 조회
- [x] 그룹 참여
