### ISSUE TITLE
[Feature]: 그룹 관리자 기능

### ISSUE THREAD

**Issue by InHyeok-J** [Endless-Creation-32nd/refill-back#16]
## 기능 설명

- 그룹 관리 현황 조회(그룹 내 정보 )
- 그룹 참가 승인 / 그룹 참가 거절
- 그룹 퇴출 기능

## Tasks

- [x] 그룹 관리자 현황 조회
- [x] 그룹 참가 승인
- [x] 그룹 참가 거절
- [x] 그룹 퇴출
