### ISSUE TITLE
[Feature]: 에러 로그 수정 및 응답 포맷 수정

### ISSUE THREAD

**Issue by InHyeok-J** [Endless-Creation-32nd/refill-back#19]
## 기능 설명

- error log 타입 수정 
- 응답 포맷 수정 -> 그룹 내 멤버 조회에 status 추가
- + JWT에 nickname 추가

## Tasks

- [x] error log 타입 수정 
- [x] 그룹 내 멤버 조회에 status 추가
- [x] JWT에 nickname 추가
